Rename subsidy_rule to rate
pieforproviders/pieforproviders pull request #1254
Opened 2021-05-16 16:39 UTC by wittejm

* and rename `subsidy_ruleable` index to `state_rule`.

Should have filed this as a regular PR earlier rather than glom it into that big WIP branch. 
  
# 💅🏼 What issue does this fix?

## 🍂 Before You Submit

* [x] updated corresponding tests

Just renaming things, no functional changes

2021-05-17 16:58 UTC, wittejm commented
Ok well I don't know why the backend tests failed here the first time. I tested again locally, changed nothing, forced-pushed for good measure, and now it passes, hooray. @katelovescode

2021-05-18 17:35 UTC, katelovescode requested changes

2021-05-18 17:35 UTC, katelovescode commented on app/models/illinois_rate.rb
> +  has_one :rate, as: :state_rule, dependent: :restrict_with_error
```suggestion
  has_one :rate, as: :rateable, dependent: :restrict_with_error
```

Couple reasons for this suggestion:
- it's "standard" syntax for polymorphics
- the state rule *is* the IllinoisRate; the polymorphic rate table record (which table will be deprecated eventually) is the generalized rate info that has nothing to do with the state.

2021-05-20 00:09 UTC, wittejm commented
Renamed, rebased, and re-ran `rake prep`

2021-05-21 14:53 UTC, katelovescode approved these changes

2021-05-21 14:53 UTC, merged