fixed jumping actions button
pieforproviders/pieforproviders pull request #2355
Opened 2022-03-11 22:47 UTC by davidcandeau

## 💅🏼 What issue does this fix?

## 🍂 Before You Submit

* [ ] Did you write & run tests and linters?
* [ ] Did you run Google Lighthouse and/or WebAIM (Wave) on UI components in your PR?
* [ ] Does your PR contain any required translations?
* [ ] Are your primary keys UUIDs on any new tables?

## 🛷 Deployment

* [ ] Migrations
* [ ] Dependencies

## 🧵 Steps to set up locally

## 🧳 Steps to test

## 🕯 Caveats, concerns

2022-03-11 22:48 UTC, davidcandeau commented on client/src/_assets/styles/payment-table-overrides.css
> +.action-icon {
@cjhaddad Let me know if there is a better way to fix this issue=

2022-03-21 20:01 UTC, cjhaddad requested changes

2022-03-21 20:01 UTC, cjhaddad commented on client/src/_assets/styles/payment-table-overrides.css
> +    min-width: 126px;
confirm that both of these rems work the same as the px, they should, but double check :)

2022-03-21 20:01 UTC, cjhaddad commented on client/src/_assets/styles/payment-table-overrides.css
> +.actionsButton {
this is a nitpick, but could you change this class name to `actions-button` to keep with naming conventions for class names?

2022-03-29 20:11 UTC, merged