Dcandeau/1622/no edit message
pieforproviders/pieforproviders pull request #2432
Opened 2022-04-04 16:58 UTC by davidcandeau

## 💅🏼 What issue does this fix?

## 🍂 Before You Submit

* [ ] Did you write & run tests and linters?
* [ ] Did you run Google Lighthouse and/or WebAIM (Wave) on UI components in your PR?
* [ ] Does your PR contain any required translations?
* [ ] Are your primary keys UUIDs on any new tables?

## 🛷 Deployment

* [ ] Migrations
* [ ] Dependencies

## 🧵 Steps to set up locally

## 🧳 Steps to test

## 🕯 Caveats, concerns

2022-04-08 23:02 UTC, katelovescode requested changes
My initial instinct is that the trigger to check if a payment has been recorded for this month yet belongs in the paymentModal component itself.  Given that eventually we'll have a drop down to select prior months, I'm not sure if there's a practical way to store "isPaymentSubmitted" from the response of submitting the payment; you might just need to make the request every time the modal opens.  

As implemented now, the page requires a refresh to display the "already submitted" message - i.e. if I submit a payment, click okay on the success message, then click "record new > payment" again, I can submit more payments.

@cjhaddad what are your thoughts on this?

2022-04-14 18:44 UTC, cjhaddad commented
> My initial instinct is that the trigger to check if a payment has been recorded for this month yet belongs in the paymentModal component itself. Given that eventually we'll have a drop down to select prior months, I'm not sure if there's a practical way to store "isPaymentSubmitted" from the response of submitting the payment; you might just need to make the request every time the modal opens.
> 
> As implemented now, the page requires a refresh to display the "already submitted" message - i.e. if I submit a payment, click okay on the success message, then click "record new > payment" again, I can submit more payments.
> 
> @cjhaddad what are your thoughts on this?



> My initial instinct is that the trigger to check if a payment has been recorded for this month yet belongs in the paymentModal component itself. Given that eventually we'll have a drop down to select prior months, I'm not sure if there's a practical way to store "isPaymentSubmitted" from the response of submitting the payment; you might just need to make the request every time the modal opens.
> 
> As implemented now, the page requires a refresh to display the "already submitted" message - i.e. if I submit a payment, click okay on the success message, then click "record new > payment" again, I can submit more payments.
> 
> @cjhaddad what are your thoughts on this?

Yes, it looks like it definitely makes sense to put the call to check if a payment is submitted needs to occur each time the Modal opens. The behavior we see now is because the call happens once and is stored in the state but not updated again after the payment modal closes and has successful submission.

2022-04-14 18:44 UTC, cjhaddad commented
> My initial instinct is that the trigger to check if a payment has been recorded for this month yet belongs in the paymentModal component itself. Given that eventually we'll have a drop down to select prior months, I'm not sure if there's a practical way to store "isPaymentSubmitted" from the response of submitting the payment; you might just need to make the request every time the modal opens.
> 
> As implemented now, the page requires a refresh to display the "already submitted" message - i.e. if I submit a payment, click okay on the success message, then click "record new > payment" again, I can submit more payments.
> 
> @cjhaddad what are your thoughts on this?



> My initial instinct is that the trigger to check if a payment has been recorded for this month yet belongs in the paymentModal component itself. Given that eventually we'll have a drop down to select prior months, I'm not sure if there's a practical way to store "isPaymentSubmitted" from the response of submitting the payment; you might just need to make the request every time the modal opens.
> 
> As implemented now, the page requires a refresh to display the "already submitted" message - i.e. if I submit a payment, click okay on the success message, then click "record new > payment" again, I can submit more payments.
> 
> @cjhaddad what are your thoughts on this?

Yes, it looks like it definitely makes sense to put the call to check if a payment is submitted needs to occur each time the Modal opens. The behavior we see now is because the call happens once and is stored in the state but not updated again after the payment modal closes and has successful submission.

2022-05-11 03:23 UTC, katelovescode commented on client/src/Payment/paymentModal.js
>  import React, { useEffect, useState } from 'react'
@davidcandeau small note for consistency, this file should be named `PaymentModal` - not sure how that slipped past us.

2022-05-17 23:41 UTC, katelovescode requested changes
Please uncommit the files as requested, but otherwise this works great.  I'll approve once the extraneous files are pulled out.

2022-05-17 23:41 UTC, katelovescode commented on app/models/attendance.rb
> +#  time_in_care(Calculated: check_out time - check_in time) :interval         not null
Don't commit these changes; I'm working to get annotate to stop doing it

2022-05-17 23:41 UTC, katelovescode commented on app/models/nebraska_dashboard_case.rb
> -#  month                      :datetime         default(Tue, 10 May 2022 19:40:48.447958000 UTC +00:00), not null
Ditto here on unrelated changes

2022-05-17 23:41 UTC, katelovescode commented on client/src/Payment/paymentModal.js
>  import React, { useEffect, useState } from 'react'
:boop: on this one, can you rename this file, please?

2022-05-17 23:41 UTC, katelovescode commented on spec/factories/attendances.rb
> +#  time_in_care(Calculated: check_out time - check_in time) :interval         not null
Ditto here, uncommit pls

2022-05-17 23:41 UTC, katelovescode commented on spec/models/attendance_spec.rb
> +#  deleted_at                                               :date
![https://media.giphy.com/media/uQZTgSuGZMTHG/giphy.gif](https://media.giphy.com/media/uQZTgSuGZMTHG/giphy.gif)

2022-05-17 23:41 UTC, katelovescode commented on db/schema.rb
> +    t.datetime "month", default: "2022-05-11 19:17:16", null: false
None of this should be committed, also same with pie_erd (I can't comment on that file because it's binary)

2022-05-20 19:50 UTC, closed without merging

2022-05-20 19:50 UTC, katelovescode commented
Reopening as a separate branch.