Add Notifications Component
pieforproviders/pieforproviders pull request #2630
Opened 2022-05-24 07:43 UTC by abdulfataiaka

## 💅🏼 What issue does this fix?

## 🍂 Before You Submit

* [ ] Did you write & run tests and linters?
* [ ] Did you run Google Lighthouse and/or WebAIM (Wave) on UI components in your PR?
* [ ] Does your PR contain any required translations?
* [ ] Are your primary keys UUIDs on any new tables?

## 🛷 Deployment

* [ ] Migrations
* [ ] Dependencies

## 🧵 Steps to set up locally

## 🧳 Steps to test

## 🕯 Caveats, concerns

2022-05-24 07:48 UTC, abdulfataiaka commented
Where to put the styles?
Is the short divider necessary?
Expected date format from server

2022-05-24 15:00 UTC, cjhaddad commented
> Where to put the styles? Is the short divider necessary? Expected date format from server

Hello! A few comments for this PR: 
-- for the styling can you use tailwind css classes instead? You then shouldn't need to worry about where to put the styles.
-- can you relocate the 'Notifications' component and test files to the Dashboards directory and delete the 'Notifications' directory? The notifications component will be used on the Dashboard view. 
-- Don't worry about adding the Notifications component to the Dashboard table, yet. This can come with the ticket that does the styling changes to the Dashboard summaries section. That said, can you remove it from the AttendanceView and restore this file? 

Thank you so much @abdulfataiaka otherwise this all looks great!

2022-05-24 15:05 UTC, cjhaddad requested changes

2022-05-24 15:05 UTC, cjhaddad commented on client/src/AttendanceView/AttendanceView.js
>  import '_assets/styles/edit-icon.css'
restore file and remove Notifications

2022-05-24 15:05 UTC, cjhaddad commented on client/src/Notifications/Notifications.js
> +const styles = {
use Tailwind css classes instead

2022-05-24 15:05 UTC, cjhaddad commented on client/src/Notifications/Notifications.js
> +import React from 'react'
relocate this component file and the test file to the 'Dashboard' directory

2022-05-26 14:59 UTC, cjhaddad approved these changes
Looks great! Thank you @abdulfataiaka !

2022-05-26 14:59 UTC, cjhaddad commented
@abdulfataiaka just rebase main and it'll be good to go.

2022-05-26 19:02 UTC, katelovescode submitted a review, later dismissed

2022-05-26 19:05 UTC, katelovescode approved these changes

2022-05-26 21:27 UTC, merged