Pie 2721/sort notifications
pieforproviders/pieforproviders pull request #2726
Opened 2022-06-16 21:41 UTC by OliverCai0

## 💅🏼 What issue does this fix?
Closes #2721, which requests that notifications be ordered chronologically based on their expiry date before they are sent. 

## 🧳 Steps to test
Added additional tests to spec/requests/api/v1/notifications_spec.rb

2022-06-17 14:17 UTC, katelovescode requested changes
Just a few cleanup requests in the code - also please remove `pie_erd` since that's not related to your change either.  The only things that should be in this PR are the controller and the spec.

2022-06-17 14:17 UTC, katelovescode commented on .gitignore
> -# Mac OS
@OliverCai0 can you remove these changes from this PR?  I don't think they're necessary

2022-06-17 14:17 UTC, katelovescode commented on db/schema.rb
> -  enable_extension "pg_stat_statements"
Also please remove this file from your PR - you didn't change the db for this feature so we shouldn't commit unrelated changes

2022-06-17 14:17 UTC, katelovescode commented on spec/requests/api/v1/notifications_spec.rb
> +    approvals = Array.new(3) { |_i| approval }
I'm a little confused about this configuration/setup, can you explain what your goal is here?

2022-06-17 16:20 UTC, OliverCai0 commented on spec/requests/api/v1/notifications_spec.rb
> +    approvals = [approval, early_approval, late_approval]
This creates three notifications with three different approval expiry times that are intentionally in the wrong order.

2022-06-17 16:41 UTC, katelovescode approved these changes

2022-06-17 19:31 UTC, katelovescode approved these changes

2022-06-18 02:59 UTC, katelovescode commented
Closing in favor of the rebase b/c this won't merge

2022-06-18 02:59 UTC, closed without merging