Pie 2599/update nebraska rates 2022
pieforproviders/pieforproviders pull request #2804
Opened 2022-07-18 19:44 UTC by OliverCai0

## 💅🏼 What issue does this fix?
Closes #2599

2022-07-20 00:06 UTC, katelovescode requested changes
This one's a doozy, let's talk through it if you need help!  Please put some time on my calendar if you need it - things are hectic now, so it's best if you grab time when you can! :)

2022-07-20 00:06 UTC, katelovescode commented on app/services/nebraska/daily/revenue_calculator.rb
> +        (hours * hourly_rate * business.ne_qris_bump(date: @date)) +
Don't need the `@` here because it's defined in the attr_reader above, so you can call it without including the instance variable indicator.

2022-07-20 00:06 UTC, katelovescode commented on spec/services/nebraska/daily/revenue_calculator_spec.rb
> +            date: '2022-7-1'.to_date,
So this is great, declarative date expectation.  If you look at the rates and effective_dates above, they're all listed as (for example) `1.month.ago` or `3.months.ago` - several of these are likely going to fail once we are 1 month or 3 months away from July 1, 2022 when the change went into effect.  You'll want to go through all of these examples and make sure that if there are expectations including qris bumps and ratings that the dates are set appropriately to calculate qris bumps before 7/1/2022, or calculate without the exponential bump after.  This is going to be a big change to this spec, make sure you're checking each example.  One of the things I do sometimes if I think specs are going to fail based on time, is literally change the time on my computer's clock (set it to 6 months in the future or 6 months in the past) and then run the specs again.  You can also do it with `travel_to` as we've seen in other specs.  This is one of the trickiest parts of handling specs in this app, all the date math - please let me know if you need help!

2022-07-20 16:50 UTC, OliverCai0 commented on app/models/nebraska_rate.rb
> +  QRIS_RATING = %w[
Sounds good to me.

2022-07-20 18:28 UTC, OliverCai0 commented on spec/services/nebraska/daily/revenue_calculator_spec.rb
> +      it 'does not default to non qris_rate based matching for hourly rates' do
I wanted to convey that 0 would be returned if the quality rating did not match. I'll change the tests to reflect that.

2022-07-25 17:46 UTC, katelovescode requested changes
Just a couple notes on clarity for the descriptions of tests, as well as one note on implementation.  Jon will need to review the rates; last time we needed this, I migrated on my local environment, ran the rate rake task, and then went into postico and downloaded a csv of the rates table and shared it with Jon to check.  Let me know if you have any questions!

2022-07-26 18:47 UTC, JonErvin commented
Hey @OliverCai0 thanks for sharing the csv file!  Took a look, overall great, have just a few edits / possible typos:

Couple High-level Qs
- It looks like max_age is 18 across the board,
- For FCC 1 and FCC 2, we broke out not_rated, step_one, and step_two separately (all the same rates) but did not for centers (just see blank quality_rating).  I assume we would need to do the same for centers, but let me know if there's a reason to keep them separate
- The name field sometimes has multiple "FCCHI" labels (e.g., `School_Age Daily LDDS FCCHIFCCHII` or `Toddler Hourly LDDS FCCHI FCCHI`)

A few small typos:
- Preschool Daily LDDS Step 3 for FCC 1 and FCC 2:  Currently $34.75, believe it should be $34.65
- School-Age Daily LDDS Step 5 for FCC 1 and FCC 2: Currently $37.50, believe it should be $37.05
- Toddler Daily OtherCounties Step 4 for Centers: Currently $38.65, believe it should be $38.60

Let me know if you have questions / want to talk through!

![image](https://user-images.githubusercontent.com/58059331/181087116-a1cd270e-fda9-471c-83b1-ef1c9cfa3d5e.png)

2022-07-28 15:45 UTC, katelovescode approved these changes

2022-07-28 15:46 UTC, merged