497/update dynamic table data
pieforproviders/pieforproviders pull request #609
Opened 2020-11-28 01:24 UTC by cjhaddad

# 💅🏼 What issue does this fix?
#575 #499 #512 #498 #497 #504 

This PR updates the Dashboard to now get all dashboard data dynamically from the API. It also updates the Dashboard tests to use the `waitFor` async utility test function, fixing the `act` warning. In order to this needed to add the ability to have jest use jsdom 16. 

## 🍂 Before You Submit

* [ X] Did you write tests?
* [ X] Did you run Google Lighthouse and/or WebAIM (Wave) on UI components in your PR?
* [ ] Does your PR contain any required translations?
* [ ] Did you run `bundle exec rspec` from the root?
* [ ] Did you run `bundle exec rails rswag` from the root?
* [ ] Did you run `bundle exec rubocop` from the root?
* [ X] Did you run `yarn lint` in `/client`?
* [ X] Did you run `yarn test` in `/client`?
* [ ] Are your primary keys UUIDs on any new tables?

## 🏺 Accessibility

## 🛷 Deployment

* [ ] Data Migrations
* [ ] Schema Migrations
* [ ] Dependencies

## 🧵 Steps to set up locally

## 🧳 Steps to test

## 🕯 Caveats, concerns

2020-11-30 23:21 UTC, katelovescode commented
![Screen Shot 2020-11-30 at 5 16 43 PM](https://user-images.githubusercontent.com/8364647/100677103-eac21700-332f-11eb-909a-218c602bcbeb.png)
Get a similar error when sorting by any revenue fields or the attendance rate

2020-11-30 23:22 UTC, katelovescode requested changes
After the sorting bug is fixed I'd like to look again!

2020-12-01 19:49 UTC, cjhaddad commented
> After the sorting bug is fixed I'd like to look again!

ah! good catch. thank you! will work on this now.

2020-12-01 20:21 UTC, cjhaddad commented
@katelovescode ready for review again. note the data coming from the backend is all the same integers for each row (as you of course know), so this currently affects testing sorting only via the UI.

2020-12-01 23:53 UTC, katelovescode approved these changes
Looks great!

2020-12-01 23:56 UTC, merged